In [1]:
!pip install numpy

In [2]:
import numpy as np

## create 1D array
arr1 = np.array([1, 2, 3, 4])
print(type(arr1))
print(arr1)
print(arr1.shape)

<class 'numpy.ndarray'>
[1 2 3 4]
(4,)


In [4]:
arr2 = np.array([1, 2, 3, 4])
arr2.reshape(1, 4)  ## 1 row 4 columns

array([[1, 2, 3, 4]])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:\n", arr.shape)
print("Dimensions:\n", arr.ndim)
print("Size:\n", arr.size)
print("Data type:\n", arr.dtype)
print("Item size:\n", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Dimensions:
 2
Size:
 6
Data type:
 int32
Item size:
 4


In [6]:
## Vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition : ",arr1+arr2)
print("Subtraction : ",arr1-arr2)
print("Multiplication : ",arr1*arr2)
print("Division : ",arr1/arr2)

Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [9]:
arr = np.array([2,3,4,5])

## square root
print(np.square(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[ 4  9 16 25]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [13]:
data = np.array([1,26,7,4,57])
data[(data>5) & (data<30)]

array([26,  7])